version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies"
    reviewers:
      - "Adamou02"
    groups:
      angular:
        patterns:
          - "@angular*"
      balkangraph:
        patterns:
          - "@balkangraph*"
      dev-dependencies:
        dependency-type: "development"
        update-types:
        - "patch"
        - "minor"
      prod-dependencies:
        dependency-type: "production"
        update-types:
        - "patch"
        - "minor"        

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
