version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies"
    reviewers:
      - "Adamou02"
    groups:
      angular:
        patterns:
        - "@angular*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
